[package]
name = "id3rs"
version = "0.1.0"
authors = ["Bas van der Hoek <bas@hoek.com>"]
edition = "2021"

[dependencies]
nom = "7"

log = "0.4"
env_logger = "0.10"

clap = "2"

tempfile = "3.2"

[dev-dependencies]
assert_matches = "1.5"

rand = "0.8"
